### ISSUE TITLE
Plugin not activating

### ISSUE THREAD

**Issue by ejschenck** [dracula/wordpress#5]
I've gotten the plugin installed in my Wordpress instance, but when activating it - nothing seems to happen.

This is on Wordpress 6.0.1.

<img width="663" alt="CleanShot 2022-08-15 at 16 22 10@2x" src="https://user-images.githubusercontent.com/18517556/184711780-61d80aef-f9c5-4b36-9d8d-f04bd5544a6f.png">

**Comment by ogustavo-pereira** [comment]
I will validate what may be happening

**Comment by rdelbem** [comment]
@ejschenck Have you activated the color scheme on you user? In order for this plugin to work, you have to go to dashboard>users>your user>Admin Color Scheme>Dracula:check, then click update profile at the bottom of the page. Please try this and tell us if it is working

**Comment by ejschenck** [comment]
Wow… funny how that works all the sudden. :)

Yeah I wasn't aware that you had to change the color scheme for the user, I thought the plugin just made a systemwide change.

Thanks for the heads up!
