### ISSUE TITLE
Install instructions are wrong after #7

### ISSUE THREAD

**Issue by lourot** [dracula/wordpress#9]
Before #7 (CC @rdelbem), the structure of the .ZIP looked like:

```
├── Dracula-custom-admin-color-schemes
│   ├── custom-admin-color-schemes.php
│   ├── dracula-bootstrap.php
│   └── smackdown
│       └── colors.css
├── INSTALL.md
├── LICENSE
├── README.md
├── repo-cloned-dev.php
└── screenshot.png
```

So the install instruction "1. Add the folder `Dracula-custom-admin-color-schemes` in your WordPress folder `./wp-content/plugin`" was correct.

Now after #7 was merged, the structure of the .ZIP looks like

```
├── dracula-custom-admin-color-schemes
│   ├── class-dracula-wordpress-custom-color-schemes.php
│   └── smackdown
│       └── colors.css
├── dracula-wordpress.php
├── README.md
└── screenshot.png
```

Meaning if one follows blindly the instructions, the file `dracula-wordpress.php` is forgotten and no plugin shows up in the list.

@rdelbem should we take `dracula-wordpress.php` back inside the folder?

**Comment by rdelbem** [comment]
Thanks for bringing this up. No, it is not necessary to move the dracula-wordpress.php back inside the folder. I fixed the install instructions in this PR https://github.com/dracula/wordpress/pull/11.
